export default Language = {
   phone: "Telefone",
   name: "Nome",
   location: "Localização",
   directions:"Rota",
   password: "Senha",
   addressDetails: "Detalhes do endereço",
   address: "Endereço",
   continue: "Continuar",

   
   just_created:"Recém criado",
   accepted_by_admin:"Aceito pelo administrador",
   accepted_by_restaurant:"Aceitar",
   assigned_to_driver:"Atribuído ao motorista",
   prepared:"Pronto",
   picked_up:"Coletado",
   delivered:"Concluído",
   rejected_by_admin:"Rejeitar",
   rejected_by_restaurant:"Rejeitar",
   updated:"Atualizado",
   closed:"Fechado",
   rejected_by_driver:"Rejeitar",
   accepted_by_driver:"Aceitar",
   prepared_order:"corrida pronto",
   prepared_order_info:"Faça esta ação somente quando o corrida estiver pronto.",
   VendorCreated:"O fornecedor foi criado",
   today:"Hoje",
   this_week:"Esta semana",
   this_month:"Este mês",
   previous_month:"Mês anterior",
   by_doing:"Fazendo",
   hi:"Olá",
   today_you_have_made:"Hoje você fez",
   earnings:"Ganhos",
   call:"Chamar",  
   directions:"Como chegar",
   deliver_order:"Corrida concluída",
   deliver_order_info:"Faça esta ação somente quando tiver entregue o corrida.",
   pickup_order:"Cliente coletado",
   pickup_order_info:"Faça esta ação somente após retirar o corrida.",
   order_is_delivered:"Faça esta ação somente quando tiver entregue o corrida.",
   order_is_paid:"O corrida já foi pago pelo cliente.",
   order_need_to_be_paid:"O corrida ainda não foi pago. O cliente precisa lhe pagar ",
   order_is_prepared:"Pronto. Você pode ir até o local para coletar o cliente.",
   you_will_earn:"Você vai ganhar:",
   no_items:"Não há itens para mostrar.",
   order_is_delivered:"Você concluiu esta corrida.",
   order_is_in_making:"No momento o corrida está em preparação. Nenhuma ação para você no momento. Com base no prazo de entrega desejado, você pode ir até o local.",
   accept_order:"Aceitar corrida",
   accept_order_info:"Esta ação aceitará a corrida.",
   reject_order:"Rejeitar corrida",
   reject_order_info:"Esta ação rejeitará a corrida",
   actions:"Ações",
   driverWorkingStatus:"Estou disponível para receber corridas",
   DriverCreated:"Obrigado por inscrever-se. A conta do motorista foi criada, mas requer aprovação do administrador. Você será contatado pelo número de telefone fornecido.",
   Restaurant: "Restaurantes",
   Client: "Cliente",
   Area: "Área",
   searchRestaurants: "O que você está procurando?",
   searchInRestaurant: "O que você procura para comer?",
   addToCart:"Adicionar ao carrinho",
   addToOrder:"Adicionar ao corrida",
   quatity:"Quantidade",
   pay_with_paypal:"PayPal",
   pay_with_paystack:"PayStack",
   pay_with_mollie:"Mollie",
   item:"Item",
   items:"Itens",
   itemAddedInCart:"O item foi adicionado ao carrinho",
   itemsAddedInCart:"Os itens adicionados ao carrinho",
   order:"corrida",
   cartSubtotal:"Subtotal do carrinho",
   subtotal:"Subtotal",
   proceedToCheckout:'Fazer o check-out',
   noOrders:'Não há corridas',
   orders:"corridas",
   noItemsInCart:'Não há itens no carrinho',
   profile:'Perfil',
   home:"Início",
   myOrders:"Meus corridas",
   addresses:"Endereços",
   login:"Entrar",
   logout:"Sair",
   forgotPassword:"Esqueceu sua senha",
   register:"Cadastre-se",
   userIsNowLoggedIn:"O usuário agora está logado",
   proceedToLoginFirst:"Entre ou cadastre-se para continuar",
   selectAddress:"Selecione o endereço",
   noAddressesAddNew:"Nenhum endereço encontrado!",
   addAddress:"Adicionar endereço",
   enterYourAddress:"Digite seu endereço",
   continue:"Continuar",
   addressDetails:"Detalhes do Endereço",
   addressNumber:"Número do endereço",
   intercom:"Interfone",
   appartment:"Nº do apartamento",
   entry:"Número da entrada",
   floor:"Andar",
   addressForDelivery:"Endereço para entrega",
   checkout:"Finalizar compra",
   deliveryOrPickup:"Entregar/Retirar",
   deliveryTime:"Prazo de entrega",
   pickupTime:"Horário de coleta",
   restaurantInformations:"Informações sobre restaurantes",
   delivery:"Entrega",
   delivered:"Entregue",
   pickup:"Pegar",
   addNewAddress:"Adicionar novo endereço",
   summary:"Resumo",
   deliveryMethod:"Método de Entrega",
   total:"Total",
   paymentMethod:"Método de pagamento",
   pay_with_card:"Pagar com cartão",
   cod:"Pagar na entrega",
   cop:"Dinheiro na coleta",
   place_order:"Fazer corrida",
   orderSuccesfull:"O corrida foi recebido com sucesso",
   trackOrder:"Você pode acompanhar e ver o status do corrida na guia de corridas.",
   ok:"Confirmar",
   cancel:"Cancelar",
   errorOnOrder:"Erro ao fazer o corrida.",
   status:"Status",
   created:"Criado", 
   orderDetails:"Detalhes do corrida",
   restaurant:"Restaurante",
   deliveryAddress:"Endereço de entrega",
   orderTracking:"Rastreamento de corridas",
   orderNumber:"Número do corrida",
   driver:"Motorista",
   driverName:"Nome do motorista",
   driverPhone:"Telefone do motorista",
   orderOptions:"Opções de corrida",
   all:"Todos",
   notifications:"Notificações",
   noNotifications:"Sem notificações",
   restaurantClosed:"Parece que o restaurante está fechado neste horário. O corrida não pode ser feito.",
   you_can_order_items_from_different_restaurants:"Você não pode pedir itens de restaurantes diferentes em um único corrida.",
   options:"Opções",
   extras:"Extras",
   notInRange:"Fora de alcance",
   selectYourCity:"Selecione sua cidade",
   drop_off:"Destino",
   distance:"Distância",
   at_location:"No local",
   inform_at_location:"Informe ao cliente que você está no local de embarque.",
   message_when_approved:"Olá, indo ao seu local de embarque",
   message_when_approved_tracking:"Aqui você pode rastrear minha localização atual ->",
   message_when_rejected:"Olá, infelizmente não poderei fazer a corrida solicitada.",
   message_at_location:"Estou no local marcado para embarque",
   client_picked_up:"Cliente embarcado",
   client_picked_up_info:"Faça esta ação quando o cliente estiver no veículo",
   change_price:"Alterar o custo",
   change_price_info:"Insira o novo custo da viagem",
   deliver_client:"Corrida concluída",
   deliver_client_info:"Faça esta ação quando terminar a viagem e certifique-se de que o preço da viagem é o exibido. Se não, você pode alterá-lo.",
   close_order:"corrida concluído",
   close_order_info:"Faça esta ação somente quando o corrida estiver totalmente realizado e pago.",
   table:"Mesa",
   deleteAccount:"Deletar conta",
   close_account:"Fechar conta",
   close_account_info:"Observe. Depois de excluir sua conta, você não conseguirá fazer login e sua conta será encerrada.",
   orders:"corridas",
   earnings:"Ganhos",
   notifications:"Notificações"
}